namespace Sales_Tracker.Classes
{
    public static class Country
    {
        // https://ofac.treasury.gov/sanctions-programs-and-country-information

        public static readonly List<SearchBox.SearchResult> countries =
        [
            new SearchBox.SearchResult("United States", Properties.Flags.United_States_of_America),
            new SearchBox.SearchResult("China", Properties.Flags.China),
            new SearchBox.SearchResult("Germany", Properties.Flags.Germany),
            new SearchBox.SearchResult("Japan", Properties.Flags.Japan),
            new SearchBox.SearchResult("United Kingdom", Properties.Flags.United_Kingdom_of_Great_Britain_and_Northern_Ireland),
            new SearchBox.SearchResult("France", Properties.Flags.France),
            new SearchBox.SearchResult("Italy", Properties.Flags.Italy),
            new SearchBox.SearchResult("Canada", Properties.Flags.Canada),

            new SearchBox.SearchResult(SearchBox.addLine, null),

            new SearchBox.SearchResult("Afghanistan", Properties.Flags.Afghanistan),
            new SearchBox.SearchResult("Albania", Properties.Flags.Albania),
            new SearchBox.SearchResult("Algeria", Properties.Flags.Algeria),
            new SearchBox.SearchResult("Andorra", Properties.Flags.Andorra),
            new SearchBox.SearchResult("Angola", Properties.Flags.Angola),
            new SearchBox.SearchResult("Antigua and Barbuda", Properties.Flags.Antigua_and_Barbuda),
            new SearchBox.SearchResult("Argentina", Properties.Flags.Argentina),
            new SearchBox.SearchResult("Armenia", Properties.Flags.Armenia),
            new SearchBox.SearchResult("Australia", Properties.Flags.Australia),
            new SearchBox.SearchResult("Austria", Properties.Flags.Austria),
            new SearchBox.SearchResult("Azerbaijan", Properties.Flags.Azerbaijan),
            new SearchBox.SearchResult("Bahamas", Properties.Flags.Bahamas),
            new SearchBox.SearchResult("Bahrain", Properties.Flags.Bahrain),
            new SearchBox.SearchResult("Bangladesh", Properties.Flags.Bangladesh),
            new SearchBox.SearchResult("Barbados", Properties.Flags.Barbados),
            new SearchBox.SearchResult("Belarus", Properties.Flags.Belarus),
            new SearchBox.SearchResult("Belgium", Properties.Flags.Belgium),
            new SearchBox.SearchResult("Belize", Properties.Flags.Belize),
            new SearchBox.SearchResult("Benin", Properties.Flags.Benin),
            new SearchBox.SearchResult("Bhutan", Properties.Flags.Bhutan),
            new SearchBox.SearchResult("Bolivia", Properties.Flags.Bolivia),
            new SearchBox.SearchResult("Bosnia and Herzegovina", Properties.Flags.Bosnia_and_Herzegovina),
            new SearchBox.SearchResult("Botswana", Properties.Flags.Botswana),
            new SearchBox.SearchResult("Brazil", Properties.Flags.Brazil),
            new SearchBox.SearchResult("Brunei", Properties.Flags.Brunei),
            new SearchBox.SearchResult("Bulgaria", Properties.Flags.Bulgaria),
            new SearchBox.SearchResult("Burkina Faso", Properties.Flags.Burkina_Faso),
            new SearchBox.SearchResult("Burundi", Properties.Flags.Burundi),
            new SearchBox.SearchResult("Cabo Verde", Properties.Flags.Cabo_Verde),
            new SearchBox.SearchResult("Cambodia", Properties.Flags.Cambodia),
            new SearchBox.SearchResult("Cameroon", Properties.Flags.Cameroon),
            new SearchBox.SearchResult("Central African Republic", Properties.Flags.Central_African_Republic),
            new SearchBox.SearchResult("Chad", Properties.Flags.Chad),
            new SearchBox.SearchResult("Chile", Properties.Flags.Chile),
            new SearchBox.SearchResult("Colombia", Properties.Flags.Colombia),
            new SearchBox.SearchResult("Comoros", Properties.Flags.Comoros),
            new SearchBox.SearchResult("Costa Rica", Properties.Flags.Costa_Rica),
            new SearchBox.SearchResult("Croatia", Properties.Flags.Croatia),
            new SearchBox.SearchResult("Cuba", Properties.Flags.Cuba),
            new SearchBox.SearchResult("Cyprus", Properties.Flags.Cyprus),
            new SearchBox.SearchResult("Czechia", Properties.Flags.Czechia),
            new SearchBox.SearchResult("Denmark", Properties.Flags.Denmark),
            new SearchBox.SearchResult("Djibouti", Properties.Flags.Djibouti),
            new SearchBox.SearchResult("Dominica", Properties.Flags.Dominica),
            new SearchBox.SearchResult("Dominican Republic", Properties.Flags.Dominican_Republic),
            new SearchBox.SearchResult("Ecuador", Properties.Flags.Ecuador),
            new SearchBox.SearchResult("Egypt", Properties.Flags.Egypt),
            new SearchBox.SearchResult("El Salvador", Properties.Flags.El_Salvador),
            new SearchBox.SearchResult("Equatorial Guinea", Properties.Flags.Equatorial_Guinea),
            new SearchBox.SearchResult("Eritrea", Properties.Flags.Eritrea),
            new SearchBox.SearchResult("Estonia", Properties.Flags.Estonia),
            new SearchBox.SearchResult("Eswatini", Properties.Flags.Eswatini),
            new SearchBox.SearchResult("Ethiopia", Properties.Flags.Ethiopia),
            new SearchBox.SearchResult("Fiji", Properties.Flags.Fiji),
            new SearchBox.SearchResult("Finland", Properties.Flags.Finland),
            new SearchBox.SearchResult("Gabon", Properties.Flags.Gabon),
            new SearchBox.SearchResult("Gambia", Properties.Flags.Gambia),
            new SearchBox.SearchResult("Georgia", Properties.Flags.Georgia),
            new SearchBox.SearchResult("Ghana", Properties.Flags.Ghana),
            new SearchBox.SearchResult("Greece", Properties.Flags.Greece),
            new SearchBox.SearchResult("Grenada", Properties.Flags.Grenada),
            new SearchBox.SearchResult("Guatemala", Properties.Flags.Guatemala),
            new SearchBox.SearchResult("Guinea", Properties.Flags.Guinea),
            new SearchBox.SearchResult("Guinea-Bissau", Properties.Flags.Guinea_Bissau),
            new SearchBox.SearchResult("Guyana", Properties.Flags.Guyana),
            new SearchBox.SearchResult("Haiti", Properties.Flags.Haiti),
            new SearchBox.SearchResult("Honduras", Properties.Flags.Honduras),
            new SearchBox.SearchResult("Hungary", Properties.Flags.Hungary),
            new SearchBox.SearchResult("Iceland", Properties.Flags.Iceland),
            new SearchBox.SearchResult("India", Properties.Flags.India),
            new SearchBox.SearchResult("Indonesia", Properties.Flags.Indonesia),
            new SearchBox.SearchResult("Iran", Properties.Flags.Iran),
            new SearchBox.SearchResult("Iraq", Properties.Flags.Iraq),
            new SearchBox.SearchResult("Ireland", Properties.Flags.Ireland),
            new SearchBox.SearchResult("Israel", Properties.Flags.Israel),
            new SearchBox.SearchResult("Ivory Coast", Properties.Flags.Ivory_Coast),
            new SearchBox.SearchResult("Jamaica", Properties.Flags.Jamaica),
            new SearchBox.SearchResult("Jordan", Properties.Flags.Jordan),
            new SearchBox.SearchResult("Kazakhstan", Properties.Flags.Kazakhstan),
            new SearchBox.SearchResult("Kenya", Properties.Flags.Kenya),
            new SearchBox.SearchResult("Kiribati", Properties.Flags.Kiribati),
            new SearchBox.SearchResult("Kuwait", Properties.Flags.Kuwait),
            new SearchBox.SearchResult("Kyrgyzstan", Properties.Flags.Kyrgyzstan),
            new SearchBox.SearchResult("Lao", Properties.Flags.Lao),
            new SearchBox.SearchResult("Latvia", Properties.Flags.Latvia),
            new SearchBox.SearchResult("Lebanon", Properties.Flags.Lebanon),
            new SearchBox.SearchResult("Lesotho", Properties.Flags.Lesotho),
            new SearchBox.SearchResult("Liberia", Properties.Flags.Liberia),
            new SearchBox.SearchResult("Libya", Properties.Flags.Libya),
            new SearchBox.SearchResult("Liechtenstein", Properties.Flags.Liechtenstein),
            new SearchBox.SearchResult("Lithuania", Properties.Flags.Lithuania),
            new SearchBox.SearchResult("Luxembourg", Properties.Flags.Luxembourg),
            new SearchBox.SearchResult("Madagascar", Properties.Flags.Madagascar),
            new SearchBox.SearchResult("Malawi", Properties.Flags.Malawi),
            new SearchBox.SearchResult("Malaysia", Properties.Flags.Malaysia),
            new SearchBox.SearchResult("Maldives", Properties.Flags.Maldives),
            new SearchBox.SearchResult("Mali", Properties.Flags.Mali),
            new SearchBox.SearchResult("Malta", Properties.Flags.Malta),
            new SearchBox.SearchResult("Marshall Islands", Properties.Flags.Marshall_Islands),
            new SearchBox.SearchResult("Mauritania", Properties.Flags.Mauritania),
            new SearchBox.SearchResult("Mauritius", Properties.Flags.Mauritius),
            new SearchBox.SearchResult("Mexico", Properties.Flags.Mexico),
            new SearchBox.SearchResult("Micronesia", Properties.Flags.Micronesia),
            new SearchBox.SearchResult("Moldova", Properties.Flags.Moldova),
            new SearchBox.SearchResult("Monaco", Properties.Flags.Monaco),
            new SearchBox.SearchResult("Mongolia", Properties.Flags.Mongolia),
            new SearchBox.SearchResult("Montenegro", Properties.Flags.Montenegro),
            new SearchBox.SearchResult("Morocco", Properties.Flags.Morocco),
            new SearchBox.SearchResult("Mozambique", Properties.Flags.Mozambique),
            new SearchBox.SearchResult("Myanmar", Properties.Flags.Myanmar),
            new SearchBox.SearchResult("Namibia", Properties.Flags.Namibia),
            new SearchBox.SearchResult("Nauru", Properties.Flags.Nauru),
            new SearchBox.SearchResult("Nepal", Properties.Flags.Nepal),
            new SearchBox.SearchResult("Netherlands", Properties.Flags.Netherlands),
            new SearchBox.SearchResult("New Zealand", Properties.Flags.New_Zealand),
            new SearchBox.SearchResult("Nicaragua", Properties.Flags.Nicaragua),
            new SearchBox.SearchResult("Niger", Properties.Flags.Niger),
            new SearchBox.SearchResult("Nigeria", Properties.Flags.Nigeria),

            // Due to international sanctions imposed on North Korea for its nuclear weapons program
            // and other illicit activities, we are required to exclude North Korea. 
            //  new SearchBox.SearchResult("North Korea", Properties.Flags.North_Korea),

            new SearchBox.SearchResult("North Macedonia", Properties.Flags.North_Macedonia),
            new SearchBox.SearchResult("Norway", Properties.Flags.Norway),
            new SearchBox.SearchResult("Oman", Properties.Flags.Oman),
            new SearchBox.SearchResult("Pakistan", Properties.Flags.Pakistan),
            new SearchBox.SearchResult("Palau", Properties.Flags.Palau),
            new SearchBox.SearchResult("Panama", Properties.Flags.Panama),
            new SearchBox.SearchResult("Papua New Guinea", Properties.Flags.Papua_New_Guinea),
            new SearchBox.SearchResult("Paraguay", Properties.Flags.Paraguay),
            new SearchBox.SearchResult("Peru", Properties.Flags.Peru),
            new SearchBox.SearchResult("Philippines", Properties.Flags.Philippines),
            new SearchBox.SearchResult("Poland", Properties.Flags.Poland),
            new SearchBox.SearchResult("Portugal", Properties.Flags.Portugal),
            new SearchBox.SearchResult("Qatar", Properties.Flags.Qatar),
            new SearchBox.SearchResult("Romania", Properties.Flags.Romania),

            // Due to international sanctions and legal regulations, we are required to exclude Russia.
            // These measures have been imposed in response to Russia's invasion of Ukraine. 
            //  new SearchBox.SearchResult("Russia", Properties.Flags.Russia),

            new SearchBox.SearchResult("Rwanda", Properties.Flags.Rwanda),
            new SearchBox.SearchResult("Saint Kitts and Nevis", Properties.Flags.Saint_Kitts_and_Nevis),
            new SearchBox.SearchResult("Saint Lucia", Properties.Flags.Saint_Lucia),
            new SearchBox.SearchResult("Saint Vincent and the Grenadines", Properties.Flags.Saint_Vincent_and_the_Grenadines),
            new SearchBox.SearchResult("Samoa", Properties.Flags.Samoa),
            new SearchBox.SearchResult("San Marino", Properties.Flags.San_Marino),
            new SearchBox.SearchResult("Sao Tome and Principe", Properties.Flags.Sao_Tome_and_Principe),
            new SearchBox.SearchResult("Saudi Arabia", Properties.Flags.Saudi_Arabia),
            new SearchBox.SearchResult("Senegal", Properties.Flags.Senegal),
            new SearchBox.SearchResult("Serbia", Properties.Flags.Serbia),
            new SearchBox.SearchResult("Seychelles", Properties.Flags.Seychelles),
            new SearchBox.SearchResult("Sierra Leone", Properties.Flags.Sierra_Leone),
            new SearchBox.SearchResult("Singapore", Properties.Flags.Singapore),
            new SearchBox.SearchResult("Slovakia", Properties.Flags.Slovakia),
            new SearchBox.SearchResult("Slovenia", Properties.Flags.Slovenia),
            new SearchBox.SearchResult("Solomon Islands", Properties.Flags.Solomon_Islands),
            new SearchBox.SearchResult("Somalia", Properties.Flags.Somalia),
            new SearchBox.SearchResult("South Africa", Properties.Flags.South_Africa),
            new SearchBox.SearchResult("South Korea", Properties.Flags.South_Korea),
            new SearchBox.SearchResult("South Sudan", Properties.Flags.South_Sudan),
            new SearchBox.SearchResult("Spain", Properties.Flags.Spain),
            new SearchBox.SearchResult("Sri Lanka", Properties.Flags.Sri_Lanka),
            new SearchBox.SearchResult("Sudan", Properties.Flags.Sudan),
            new SearchBox.SearchResult("Suriname", Properties.Flags.Suriname),
            new SearchBox.SearchResult("Sweden", Properties.Flags.Sweden),
            new SearchBox.SearchResult("Switzerland", Properties.Flags.Switzerland),
            new SearchBox.SearchResult("Syria", Properties.Flags.Syria),
            new SearchBox.SearchResult("Taiwan", Properties.Flags.Taiwan),
            new SearchBox.SearchResult("Tajikistan", Properties.Flags.Tajikistan),
            new SearchBox.SearchResult("Tanzania", Properties.Flags.Tanzania),
            new SearchBox.SearchResult("Thailand", Properties.Flags.Thailand),
            new SearchBox.SearchResult("The Democratic Republic of the Congo", Properties.Flags.The_Democratic_Republic_of_the_Congo),
            new SearchBox.SearchResult("The Republic of the Congo", Properties.Flags.The_Republic_of_the_Congo),
            new SearchBox.SearchResult("Timor-Leste", Properties.Flags.Timor_Leste),
            new SearchBox.SearchResult("Togo", Properties.Flags.Togo),
            new SearchBox.SearchResult("Tonga", Properties.Flags.Tonga),
            new SearchBox.SearchResult("Trinidad and Tobago", Properties.Flags.Trinidad_and_Tobago),
            new SearchBox.SearchResult("Tunisia", Properties.Flags.Tunisia),
            new SearchBox.SearchResult("Turkey", Properties.Flags.Turkey),
            new SearchBox.SearchResult("Turkmenistan", Properties.Flags.Turkmenistan),
            new SearchBox.SearchResult("Tuvalu", Properties.Flags.Tuvalu),
            new SearchBox.SearchResult("Uganda", Properties.Flags.Uganda),
            new SearchBox.SearchResult("Ukraine", Properties.Flags.Ukraine),
            new SearchBox.SearchResult("United Arab Emirates", Properties.Flags.United_Arab_Emirates),
            new SearchBox.SearchResult("Uruguay", Properties.Flags.Uruguay),
            new SearchBox.SearchResult("Uzbekistan", Properties.Flags.Uzbekistan),
            new SearchBox.SearchResult("Vanuatu", Properties.Flags.Vanuatu),
            new SearchBox.SearchResult("Venezuela", Properties.Flags.Venezuela),
            new SearchBox.SearchResult("Vietnam", Properties.Flags.Vietnam),
            new SearchBox.SearchResult("Western Sahara", Properties.Flags.Western_Sahara),
            new SearchBox.SearchResult("Yemen", Properties.Flags.Yemen),
            new SearchBox.SearchResult("Zambia", Properties.Flags.Zambia),
            new SearchBox.SearchResult("Zimbabwe", Properties.Flags.Zimbabwe)
        ];
    }
}