using Sales_Tracker.UI;

namespace Sales_Tracker.DataClasses
{
    public static class Country
    {
        // https://ofac.treasury.gov/sanctions-programs-and-country-information

        public static readonly List<SearchResult> countries =
        [
            new SearchResult("Unkown", null, 0),
            new SearchResult("United States", Properties.Flags.United_States_of_America, 0),
            new SearchResult("China", Properties.Flags.China, 0),
            new SearchResult("Japan", Properties.Flags.Japan, 0),
            new SearchResult("Germany", Properties.Flags.Germany, 0),
            new SearchResult("United Kingdom", Properties.Flags.United_Kingdom_of_Great_Britain_and_Northern_Ireland, 0),
            new SearchResult("France", Properties.Flags.France, 0),
            new SearchResult("Italy", Properties.Flags.Italy, 0),
            new SearchResult("Canada", Properties.Flags.Canada, 0),

            new SearchResult(SearchBox.addLine, null, 0),

            new SearchResult("Afghanistan", Properties.Flags.Afghanistan, 0),
            new SearchResult("Albania", Properties.Flags.Albania, 0),
            new SearchResult("Algeria", Properties.Flags.Algeria, 0),
            new SearchResult("Andorra", Properties.Flags.Andorra, 0),
            new SearchResult("Angola", Properties.Flags.Angola, 0),
            new SearchResult("Antigua and Barbuda", Properties.Flags.Antigua_and_Barbuda, 0),
            new SearchResult("Argentina", Properties.Flags.Argentina, 0),
            new SearchResult("Armenia", Properties.Flags.Armenia, 0),
            new SearchResult("Australia", Properties.Flags.Australia, 0),
            new SearchResult("Austria", Properties.Flags.Austria, 0),
            new SearchResult("Azerbaijan", Properties.Flags.Azerbaijan, 0),
            new SearchResult("Bahamas", Properties.Flags.Bahamas, 0),
            new SearchResult("Bahrain", Properties.Flags.Bahrain, 0),
            new SearchResult("Bangladesh", Properties.Flags.Bangladesh, 0),
            new SearchResult("Barbados", Properties.Flags.Barbados, 0),
            new SearchResult("Belarus", Properties.Flags.Belarus, 0),
            new SearchResult("Belgium", Properties.Flags.Belgium, 0),
            new SearchResult("Belize", Properties.Flags.Belize, 0),
            new SearchResult("Benin", Properties.Flags.Benin, 0),
            new SearchResult("Bhutan", Properties.Flags.Bhutan, 0),
            new SearchResult("Bolivia", Properties.Flags.Bolivia, 0),
            new SearchResult("Bosnia and Herzegovina", Properties.Flags.Bosnia_and_Herzegovina, 0),
            new SearchResult("Botswana", Properties.Flags.Botswana, 0),
            new SearchResult("Brazil", Properties.Flags.Brazil, 0),
            new SearchResult("Brunei", Properties.Flags.Brunei, 0),
            new SearchResult("Bulgaria", Properties.Flags.Bulgaria, 0),
            new SearchResult("Burkina Faso", Properties.Flags.Burkina_Faso, 0),
            new SearchResult("Burundi", Properties.Flags.Burundi, 0),
            new SearchResult("Cabo Verde", Properties.Flags.Cabo_Verde, 0),
            new SearchResult("Cambodia", Properties.Flags.Cambodia, 0),
            new SearchResult("Cameroon", Properties.Flags.Cameroon, 0),
            new SearchResult("Central African Republic", Properties.Flags.Central_African_Republic, 0),
            new SearchResult("Chad", Properties.Flags.Chad, 0),
            new SearchResult("Chile", Properties.Flags.Chile, 0),
            new SearchResult("Colombia", Properties.Flags.Colombia, 0),
            new SearchResult("Comoros", Properties.Flags.Comoros, 0),
            new SearchResult("Costa Rica", Properties.Flags.Costa_Rica, 0),
            new SearchResult("Croatia", Properties.Flags.Croatia, 0),
            new SearchResult("Cuba", Properties.Flags.Cuba, 0),
            new SearchResult("Cyprus", Properties.Flags.Cyprus, 0),
            new SearchResult("Czechia", Properties.Flags.Czechia, 0),
            new SearchResult("Denmark", Properties.Flags.Denmark, 0),
            new SearchResult("Djibouti", Properties.Flags.Djibouti, 0),
            new SearchResult("Dominica", Properties.Flags.Dominica, 0),
            new SearchResult("Dominican Republic", Properties.Flags.Dominican_Republic, 0),
            new SearchResult("Ecuador", Properties.Flags.Ecuador, 0),
            new SearchResult("Egypt", Properties.Flags.Egypt, 0),
            new SearchResult("El Salvador", Properties.Flags.El_Salvador, 0),
            new SearchResult("Equatorial Guinea", Properties.Flags.Equatorial_Guinea, 0),
            new SearchResult("Eritrea", Properties.Flags.Eritrea, 0),
            new SearchResult("Estonia", Properties.Flags.Estonia, 0),
            new SearchResult("Eswatini", Properties.Flags.Eswatini, 0),
            new SearchResult("Ethiopia", Properties.Flags.Ethiopia, 0),
            new SearchResult("Fiji", Properties.Flags.Fiji, 0),
            new SearchResult("Finland", Properties.Flags.Finland, 0),
            new SearchResult("Gabon", Properties.Flags.Gabon, 0),
            new SearchResult("Gambia", Properties.Flags.Gambia, 0),
            new SearchResult("Georgia", Properties.Flags.Georgia, 0),
            new SearchResult("Ghana", Properties.Flags.Ghana, 0),
            new SearchResult("Greece", Properties.Flags.Greece, 0),
            new SearchResult("Grenada", Properties.Flags.Grenada, 0),
            new SearchResult("Guatemala", Properties.Flags.Guatemala, 0),
            new SearchResult("Guinea", Properties.Flags.Guinea, 0),
            new SearchResult("Guinea-Bissau", Properties.Flags.Guinea_Bissau, 0),
            new SearchResult("Guyana", Properties.Flags.Guyana, 0),
            new SearchResult("Haiti", Properties.Flags.Haiti, 0),
            new SearchResult("Honduras", Properties.Flags.Honduras, 0),
            new SearchResult("Hungary", Properties.Flags.Hungary, 0),
            new SearchResult("Iceland", Properties.Flags.Iceland, 0),
            new SearchResult("India", Properties.Flags.India, 0),
            new SearchResult("Indonesia", Properties.Flags.Indonesia, 0),
            new SearchResult("Iran", Properties.Flags.Iran, 0),
            new SearchResult("Iraq", Properties.Flags.Iraq, 0),
            new SearchResult("Ireland", Properties.Flags.Ireland, 0),
            new SearchResult("Israel", Properties.Flags.Israel, 0),
            new SearchResult("Ivory Coast", Properties.Flags.Ivory_Coast, 0),
            new SearchResult("Jamaica", Properties.Flags.Jamaica, 0),
            new SearchResult("Jordan", Properties.Flags.Jordan, 0),
            new SearchResult("Kazakhstan", Properties.Flags.Kazakhstan, 0),
            new SearchResult("Kenya", Properties.Flags.Kenya, 0),
            new SearchResult("Kiribati", Properties.Flags.Kiribati, 0),
            new SearchResult("Kuwait", Properties.Flags.Kuwait, 0),
            new SearchResult("Kyrgyzstan", Properties.Flags.Kyrgyzstan, 0),
            new SearchResult("Lao", Properties.Flags.Lao, 0),
            new SearchResult("Latvia", Properties.Flags.Latvia, 0),
            new SearchResult("Lebanon", Properties.Flags.Lebanon, 0),
            new SearchResult("Lesotho", Properties.Flags.Lesotho, 0),
            new SearchResult("Liberia", Properties.Flags.Liberia, 0),
            new SearchResult("Libya", Properties.Flags.Libya, 0),
            new SearchResult("Liechtenstein", Properties.Flags.Liechtenstein, 0),
            new SearchResult("Lithuania", Properties.Flags.Lithuania, 0),
            new SearchResult("Luxembourg", Properties.Flags.Luxembourg, 0),
            new SearchResult("Madagascar", Properties.Flags.Madagascar, 0),
            new SearchResult("Malawi", Properties.Flags.Malawi, 0),
            new SearchResult("Malaysia", Properties.Flags.Malaysia, 0),
            new SearchResult("Maldives", Properties.Flags.Maldives, 0),
            new SearchResult("Mali", Properties.Flags.Mali, 0),
            new SearchResult("Malta", Properties.Flags.Malta, 0),
            new SearchResult("Marshall Islands", Properties.Flags.Marshall_Islands, 0),
            new SearchResult("Mauritania", Properties.Flags.Mauritania, 0),
            new SearchResult("Mauritius", Properties.Flags.Mauritius, 0),
            new SearchResult("Mexico", Properties.Flags.Mexico, 0),
            new SearchResult("Micronesia", Properties.Flags.Micronesia, 0),
            new SearchResult("Moldova", Properties.Flags.Moldova, 0),
            new SearchResult("Monaco", Properties.Flags.Monaco, 0),
            new SearchResult("Mongolia", Properties.Flags.Mongolia, 0),
            new SearchResult("Montenegro", Properties.Flags.Montenegro, 0),
            new SearchResult("Morocco", Properties.Flags.Morocco, 0),
            new SearchResult("Mozambique", Properties.Flags.Mozambique, 0),
            new SearchResult("Myanmar", Properties.Flags.Myanmar, 0),
            new SearchResult("Namibia", Properties.Flags.Namibia, 0),
            new SearchResult("Nauru", Properties.Flags.Nauru, 0),
            new SearchResult("Nepal", Properties.Flags.Nepal, 0),
            new SearchResult("Netherlands", Properties.Flags.Netherlands, 0),
            new SearchResult("New Zealand", Properties.Flags.New_Zealand, 0),
            new SearchResult("Nicaragua", Properties.Flags.Nicaragua, 0),
            new SearchResult("Niger", Properties.Flags.Niger, 0),
            new SearchResult("Nigeria", Properties.Flags.Nigeria, 0),

            // Due to international sanctions imposed on North Korea for its nuclear weapons program
            // and other illicit activities, we are required to exclude North Korea.
            //  new SearchResult("North Korea", Properties.Flags.North_Korea, 0),

            new SearchResult("North Macedonia", Properties.Flags.North_Macedonia, 0),
            new SearchResult("Norway", Properties.Flags.Norway, 0),
            new SearchResult("Oman", Properties.Flags.Oman, 0),
            new SearchResult("Pakistan", Properties.Flags.Pakistan, 0),
            new SearchResult("Palau", Properties.Flags.Palau, 0),
            new SearchResult("Panama", Properties.Flags.Panama, 0),
            new SearchResult("Papua New Guinea", Properties.Flags.Papua_New_Guinea, 0),
            new SearchResult("Paraguay", Properties.Flags.Paraguay, 0),
            new SearchResult("Peru", Properties.Flags.Peru, 0),
            new SearchResult("Philippines", Properties.Flags.Philippines, 0),
            new SearchResult("Poland", Properties.Flags.Poland, 0),
            new SearchResult("Portugal", Properties.Flags.Portugal, 0),
            new SearchResult("Qatar", Properties.Flags.Qatar, 0),
            new SearchResult("Romania", Properties.Flags.Romania, 0),

            // Due to international sanctions and legal regulations, we are required to exclude Russia.
            // These measures have been imposed in response to Russia's invasion of Ukraine.
            //  new SearchResult("Russia", Properties.Flags.Russia, 0),

            new SearchResult("Rwanda", Properties.Flags.Rwanda, 0),
            new SearchResult("Saint Kitts and Nevis", Properties.Flags.Saint_Kitts_and_Nevis, 0),
            new SearchResult("Saint Lucia", Properties.Flags.Saint_Lucia, 0),
            new SearchResult("Saint Vincent and the Grenadines", Properties.Flags.Saint_Vincent_and_the_Grenadines, 0),
            new SearchResult("Samoa", Properties.Flags.Samoa, 0),
            new SearchResult("San Marino", Properties.Flags.San_Marino, 0),
            new SearchResult("Sao Tome and Principe", Properties.Flags.Sao_Tome_and_Principe, 0),
            new SearchResult("Saudi Arabia", Properties.Flags.Saudi_Arabia, 0),
            new SearchResult("Senegal", Properties.Flags.Senegal, 0),
            new SearchResult("Serbia", Properties.Flags.Serbia, 0),
            new SearchResult("Seychelles", Properties.Flags.Seychelles, 0),
            new SearchResult("Sierra Leone", Properties.Flags.Sierra_Leone, 0),
            new SearchResult("Singapore", Properties.Flags.Singapore, 0),
            new SearchResult("Slovakia", Properties.Flags.Slovakia, 0),
            new SearchResult("Slovenia", Properties.Flags.Slovenia, 0),
            new SearchResult("Solomon Islands", Properties.Flags.Solomon_Islands, 0),
            new SearchResult("Somalia", Properties.Flags.Somalia, 0),
            new SearchResult("South Africa", Properties.Flags.South_Africa, 0),
            new SearchResult("South Korea", Properties.Flags.South_Korea, 0),
            new SearchResult("South Sudan", Properties.Flags.South_Sudan, 0),
            new SearchResult("Spain", Properties.Flags.Spain, 0),
            new SearchResult("Sri Lanka", Properties.Flags.Sri_Lanka, 0),
            new SearchResult("Sudan", Properties.Flags.Sudan, 0),
            new SearchResult("Suriname", Properties.Flags.Suriname, 0),
            new SearchResult("Sweden", Properties.Flags.Sweden, 0),
            new SearchResult("Switzerland", Properties.Flags.Switzerland, 0),
            new SearchResult("Syria", Properties.Flags.Syria, 0),
            new SearchResult("Taiwan", Properties.Flags.Taiwan, 0),
            new SearchResult("Tajikistan", Properties.Flags.Tajikistan, 0),
            new SearchResult("Tanzania", Properties.Flags.Tanzania, 0),
            new SearchResult("Thailand", Properties.Flags.Thailand, 0),
            new SearchResult("The Democratic Republic of the Congo", Properties.Flags.The_Democratic_Republic_of_the_Congo, 0),
            new SearchResult("The Republic of the Congo", Properties.Flags.The_Republic_of_the_Congo, 0),
            new SearchResult("Timor-Leste", Properties.Flags.Timor_Leste, 0),
            new SearchResult("Togo", Properties.Flags.Togo, 0),
            new SearchResult("Tonga", Properties.Flags.Tonga, 0),
            new SearchResult("Trinidad and Tobago", Properties.Flags.Trinidad_and_Tobago, 0),
            new SearchResult("Tunisia", Properties.Flags.Tunisia, 0),
            new SearchResult("Turkey", Properties.Flags.Turkey, 0),
            new SearchResult("Turkmenistan", Properties.Flags.Turkmenistan, 0),
            new SearchResult("Tuvalu", Properties.Flags.Tuvalu, 0),
            new SearchResult("Uganda", Properties.Flags.Uganda, 0),
            new SearchResult("Ukraine", Properties.Flags.Ukraine, 0),
            new SearchResult("United Arab Emirates", Properties.Flags.United_Arab_Emirates, 0),
            new SearchResult("Uruguay", Properties.Flags.Uruguay, 0),
            new SearchResult("Uzbekistan", Properties.Flags.Uzbekistan, 0),
            new SearchResult("Vanuatu", Properties.Flags.Vanuatu, 0),
            new SearchResult("Venezuela", Properties.Flags.Venezuela, 0),
            new SearchResult("Vietnam", Properties.Flags.Vietnam, 0),
            new SearchResult("Western Sahara", Properties.Flags.Western_Sahara, 0),
            new SearchResult("Yemen", Properties.Flags.Yemen, 0),
            new SearchResult("Zambia", Properties.Flags.Zambia, 0),
            new SearchResult("Zimbabwe", Properties.Flags.Zimbabwe ,0)
        ];
    }
}